//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Defaults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Defaults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Resources.Defaults", typeof(Defaults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 212.36.82.130.
        /// </summary>
        public static string FTPHost {
            get {
                return ResourceManager.GetString("FTPHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQanoni1.
        /// </summary>
        public static string FTPPwd {
            get {
                return ResourceManager.GetString("FTPPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQanonimo.
        /// </summary>
        public static string FTPUser {
            get {
                return ResourceManager.GetString("FTPUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ASIGNADO.
        /// </summary>
        public static string NO_VALUE {
            get {
                return ResourceManager.GetString("NO_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000000000.
        /// </summary>
        public static string PATH_FORMAT {
            get {
                return ResourceManager.GetString("PATH_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SCHEMA {
            get {
                return ResourceManager.GetString("SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        public static string SCHEMA_CODE_FORMAT {
            get {
                return ResourceManager.GetString("SCHEMA_CODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-ES.
        /// </summary>
        public static string SPANISH_CULTURE_CODE {
            get {
                return ResourceManager.GetString("SPANISH_CULTURE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000.
        /// </summary>
        public static string USER_CODE_FORMAT {
            get {
                return ResourceManager.GetString("USER_CODE_FORMAT", resourceCulture);
            }
        }
    }
}
