//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string EComponentStatus_ERROR {
            get {
                return ResourceManager.GetString("EComponentStatus_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTIFIED.
        /// </summary>
        internal static string EComponentStatus_NOTIFIED {
            get {
                return ResourceManager.GetString("EComponentStatus_NOTIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EComponentStatus_OK {
            get {
                return ResourceManager.GetString("EComponentStatus_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY.
        /// </summary>
        internal static string EComponentStatus_READY {
            get {
                return ResourceManager.GetString("EComponentStatus_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNAVAILABLE.
        /// </summary>
        internal static string EComponentStatus_UNAVAILABLE {
            get {
                return ResourceManager.GetString("EComponentStatus_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKING.
        /// </summary>
        internal static string EComponentStatus_WORKING {
            get {
                return ResourceManager.GetString("EComponentStatus_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CABINET.
        /// </summary>
        internal static string EComponentType_Cabinet {
            get {
                return ResourceManager.GetString("EComponentType_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINAL.
        /// </summary>
        internal static string EComponentType_Terminal {
            get {
                return ResourceManager.GetString("EComponentType_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB SERVICE.
        /// </summary>
        internal static string EComponentType_WebService {
            get {
                return ResourceManager.GetString("EComponentType_WebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINDOWS SERVICE.
        /// </summary>
        internal static string EComponentType_WinService {
            get {
                return ResourceManager.GetString("EComponentType_WinService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRITICAL.
        /// </summary>
        internal static string EErrorLevel_CRITICAL {
            get {
                return ResourceManager.GetString("EErrorLevel_CRITICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ERROR.
        /// </summary>
        internal static string EErrorLevel_OK {
            get {
                return ResourceManager.GetString("EErrorLevel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string EErrorLevel_WARNING {
            get {
                return ResourceManager.GetString("EErrorLevel_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string EEstadoItem_Active {
            get {
                return ResourceManager.GetString("EEstadoItem_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        internal static string EEstadoItem_Anulado {
            get {
                return ResourceManager.GetString("EEstadoItem_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string EEstadoItem_Baja {
            get {
                return ResourceManager.GetString("EEstadoItem_Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contabilizado.
        /// </summary>
        internal static string EEstadoItem_Contabilizado {
            get {
                return ResourceManager.GetString("EEstadoItem_Contabilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitido.
        /// </summary>
        internal static string EEstadoItem_Emitido {
            get {
                return ResourceManager.GetString("EEstadoItem_Emitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string EEstadoItem_Inactive {
            get {
                return ResourceManager.GetString("EEstadoItem_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        internal static string EEstadoItem_LockedOut {
            get {
                return ResourceManager.GetString("EEstadoItem_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        internal static string EEstadoItem_Registered {
            get {
                return ResourceManager.GetString("EEstadoItem_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierto.
        /// </summary>
        internal static string EEstadoItem_Unlock {
            get {
                return ResourceManager.GetString("EEstadoItem_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string EPrivilege_Create {
            get {
                return ResourceManager.GetString("EPrivilege_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string EPrivilege_Delete {
            get {
                return ResourceManager.GetString("EPrivilege_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string EPrivilege_Modify {
            get {
                return ResourceManager.GetString("EPrivilege_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectura.
        /// </summary>
        internal static string EPrivilege_Read {
            get {
                return ResourceManager.GetString("EPrivilege_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones Correctoras.
        /// </summary>
        internal static string ESecureItem_Accion_Correctora {
            get {
                return ResourceManager.GetString("ESecureItem_Accion_Correctora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actas del Comité de Calidad.
        /// </summary>
        internal static string ESecureItem_Acta_Comite_Calidad {
            get {
                return ResourceManager.GetString("ESecureItem_Acta_Comite_Calidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Emitidos.
        /// </summary>
        internal static string ESecureItem_Albaran_Emitido {
            get {
                return ResourceManager.GetString("ESecureItem_Albaran_Emitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Recibidos.
        /// </summary>
        internal static string ESecureItem_Albaran_Recibido {
            get {
                return ResourceManager.GetString("ESecureItem_Albaran_Recibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenes.
        /// </summary>
        internal static string ESecureItem_Almacen {
            get {
                return ResourceManager.GetString("ESecureItem_Almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnos.
        /// </summary>
        internal static string ESecureItem_Alumno {
            get {
                return ResourceManager.GetString("ESecureItem_Alumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampliaciones.
        /// </summary>
        internal static string ESecureItem_Ampliacion {
            get {
                return ResourceManager.GetString("ESecureItem_Ampliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas.
        /// </summary>
        internal static string ESecureItem_Area {
            get {
                return ResourceManager.GetString("ESecureItem_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditar Movimientos Bancarios.
        /// </summary>
        internal static string ESecureItem_AuditarMovimientos {
            get {
                return ResourceManager.GetString("ESecureItem_AuditarMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditorías.
        /// </summary>
        internal static string ESecureItem_Auditoria {
            get {
                return ResourceManager.GetString("ESecureItem_Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinas.
        /// </summary>
        internal static string ESecureItem_Cabinet {
            get {
                return ResourceManager.GetString("ESecureItem_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajas.
        /// </summary>
        internal static string ESecureItem_Caja {
            get {
                return ResourceManager.GetString("ESecureItem_Caja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases de Auditorías.
        /// </summary>
        internal static string ESecureItem_Clase_Auditoria {
            get {
                return ResourceManager.GetString("ESecureItem_Clase_Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string ESecureItem_Cliente {
            get {
                return ResourceManager.GetString("ESecureItem_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros.
        /// </summary>
        internal static string ESecureItem_Cobro {
            get {
                return ResourceManager.GetString("ESecureItem_Cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Contables.
        /// </summary>
        internal static string ESecureItem_CuentaContable {
            get {
                return ResourceManager.GetString("ESecureItem_CuentaContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        internal static string ESecureItem_Curso {
            get {
                return ResourceManager.GetString("ESecureItem_Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de Formación.
        /// </summary>
        internal static string ESecureItem_Curso_Formacion {
            get {
                return ResourceManager.GetString("ESecureItem_Curso_Formacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancias.
        /// </summary>
        internal static string ESecureItem_Discrepancia {
            get {
                return ResourceManager.GetString("ESecureItem_Discrepancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string ESecureItem_Documento {
            get {
                return ResourceManager.GetString("ESecureItem_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string ESecureItem_Empleado {
            get {
                return ResourceManager.GetString("ESecureItem_Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        internal static string ESecureItem_Empresa {
            get {
                return ResourceManager.GetString("ESecureItem_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear Estado.
        /// </summary>
        internal static string ESecureItem_Estado {
            get {
                return ResourceManager.GetString("ESecureItem_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes.
        /// </summary>
        internal static string ESecureItem_Examen {
            get {
                return ResourceManager.GetString("ESecureItem_Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedientes.
        /// </summary>
        internal static string ESecureItem_Expediente {
            get {
                return ResourceManager.GetString("ESecureItem_Expediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Emitidas.
        /// </summary>
        internal static string ESecureItem_Factura_Emitida {
            get {
                return ResourceManager.GetString("ESecureItem_Factura_Emitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas.
        /// </summary>
        internal static string ESecureItem_Factura_Recibida {
            get {
                return ResourceManager.GetString("ESecureItem_Factura_Recibida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos.
        /// </summary>
        internal static string ESecureItem_Gasto {
            get {
                return ResourceManager.GetString("ESecureItem_Gasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios.
        /// </summary>
        internal static string ESecureItem_Horario {
            get {
                return ResourceManager.GetString("ESecureItem_Horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidencias.
        /// </summary>
        internal static string ESecureItem_Incidencia {
            get {
                return ResourceManager.GetString("ESecureItem_Incidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes.
        /// </summary>
        internal static string ESecureItem_Informe {
            get {
                return ResourceManager.GetString("ESecureItem_Informe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructores.
        /// </summary>
        internal static string ESecureItem_Instructor {
            get {
                return ResourceManager.GetString("ESecureItem_Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Docente.
        /// </summary>
        internal static string ESecureItem_Material_Docente {
            get {
                return ResourceManager.GetString("ESecureItem_Material_Docente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        internal static string ESecureItem_Modulo {
            get {
                return ResourceManager.GetString("ESecureItem_Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos a Bancos.
        /// </summary>
        internal static string ESecureItem_Movimiento_Banco {
            get {
                return ResourceManager.GetString("ESecureItem_Movimiento_Banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nóminas.
        /// </summary>
        internal static string ESecureItem_Nomina {
            get {
                return ResourceManager.GetString("ESecureItem_Nomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        internal static string ESecureItem_Pago {
            get {
                return ResourceManager.GetString("ESecureItem_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de Asistencia.
        /// </summary>
        internal static string ESecureItem_Parte_Asistencia {
            get {
                return ResourceManager.GetString("ESecureItem_Parte_Asistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string ESecureItem_Partner {
            get {
                return ResourceManager.GetString("ESecureItem_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Anuales.
        /// </summary>
        internal static string ESecureItem_Plan_Anual {
            get {
                return ResourceManager.GetString("ESecureItem_Plan_Anual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de Estudios.
        /// </summary>
        internal static string ESecureItem_Plan_Estudios {
            get {
                return ResourceManager.GetString("ESecureItem_Plan_Estudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Extra.
        /// </summary>
        internal static string ESecureItem_Plan_Extra {
            get {
                return ResourceManager.GetString("ESecureItem_Plan_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string ESecureItem_Producto {
            get {
                return ResourceManager.GetString("ESecureItem_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuestos / Proformas.
        /// </summary>
        internal static string ESecureItem_Proforma {
            get {
                return ResourceManager.GetString("ESecureItem_Proforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        internal static string ESecureItem_Promocion {
            get {
                return ResourceManager.GetString("ESecureItem_Promocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string ESecureItem_Proveedor {
            get {
                return ResourceManager.GetString("ESecureItem_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string ESecureItem_Serie {
            get {
                return ResourceManager.GetString("ESecureItem_Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ESecureItem_Stock {
            get {
                return ResourceManager.GetString("ESecureItem_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscripción.
        /// </summary>
        internal static string ESecureItem_Suscription {
            get {
                return ResourceManager.GetString("ESecureItem_Suscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablas Auxiliares.
        /// </summary>
        internal static string ESecureItem_Tabla_Auxiliar {
            get {
                return ResourceManager.GetString("ESecureItem_Tabla_Auxiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        internal static string ESecureItem_Transaction {
            get {
                return ResourceManager.GetString("ESecureItem_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string ESecureItem_Variable {
            get {
                return ResourceManager.GetString("ESecureItem_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        internal static string ESMSGateway_All {
            get {
                return ResourceManager.GetString("ESMSGateway_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esendex.
        /// </summary>
        internal static string ESMSGateway_Esendex {
            get {
                return ResourceManager.GetString("ESMSGateway_Esendex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        internal static string EStepGraph_Day {
            get {
                return ResourceManager.GetString("EStepGraph_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string EStepGraph_Hour {
            get {
                return ResourceManager.GetString("EStepGraph_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string EStepGraph_Month {
            get {
                return ResourceManager.GetString("EStepGraph_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        internal static string EStepGraph_None {
            get {
                return ResourceManager.GetString("EStepGraph_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string EStepGraph_Week {
            get {
                return ResourceManager.GetString("EStepGraph_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string EStepGraph_Year {
            get {
                return ResourceManager.GetString("EStepGraph_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string EValue_All {
            get {
                return ResourceManager.GetString("EValue_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto.
        /// </summary>
        internal static string EValue_Default {
            get {
                return ResourceManager.GetString("EValue_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin valor.
        /// </summary>
        internal static string EValue_Empty {
            get {
                return ResourceManager.GetString("EValue_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entre.
        /// </summary>
        internal static string OPERATION_BETWEEN {
            get {
                return ResourceManager.GetString("OPERATION_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contiene.
        /// </summary>
        internal static string OPERATION_CONTAINS {
            get {
                return ResourceManager.GetString("OPERATION_CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distinto.
        /// </summary>
        internal static string OPERATION_DISTINCT {
            get {
                return ResourceManager.GetString("OPERATION_DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string OPERATION_EQUAL {
            get {
                return ResourceManager.GetString("OPERATION_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string OPERATION_GREATER {
            get {
                return ResourceManager.GetString("OPERATION_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string OPERATION_GREATEROREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_GREATEROREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string OPERATION_LESS {
            get {
                return ResourceManager.GetString("OPERATION_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string OPERATION_LESSOREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_LESSOREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contiene.
        /// </summary>
        internal static string OPERATION_OP_CONTAINS {
            get {
                return ResourceManager.GetString("OPERATION_OP_CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string OPERATION_OP_DISTINCT {
            get {
                return ResourceManager.GetString("OPERATION_OP_DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string OPERATION_OP_EQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string OPERATION_OP_GREATER {
            get {
                return ResourceManager.GetString("OPERATION_OP_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string OPERATION_OP_GREATEROREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_GREATEROREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string OPERATION_OP_LESS {
            get {
                return ResourceManager.GetString("OPERATION_OP_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string OPERATION_OP_LESSOREQUAL {
            get {
                return ResourceManager.GetString("OPERATION_OP_LESSOREQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empieza por.
        /// </summary>
        internal static string OPERATION_OP_STARTSWITH {
            get {
                return ResourceManager.GetString("OPERATION_OP_STARTSWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empieza por.
        /// </summary>
        internal static string OPERATION_STARTSWITH {
            get {
                return ResourceManager.GetString("OPERATION_STARTSWITH", resourceCulture);
            }
        }
    }
}
