//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la aplicación de creación de copias de seguridad..
        /// </summary>
        public static string BACKUP_APP_NOT_FOUND {
            get {
                return ResourceManager.GetString("BACKUP_APP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al generar la copia de seguridad..
        /// </summary>
        public static string BACKUP_ERROR {
            get {
                return ResourceManager.GetString("BACKUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible cambiar su contraseña
        ///Compruebe que ha escrito correctamente su contraseña actual.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible cambiar su código pin
        ///Compruebe que ha escrito correctamente su pin actual.
        /// </summary>
        public static string CHANGE_PIN {
            get {
                return ResourceManager.GetString("CHANGE_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error intentando cerrar una sesión..
        /// </summary>
        public static string CLOSE_SESSION_ERROR {
            get {
                return ResourceManager.GetString("CLOSE_SESSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la propiedad &quot;{0}&quot; en el tipo &quot;{1}&quot;.
        /// </summary>
        public static string COLUMN_NOT_FOUND {
            get {
                return ResourceManager.GetString("COLUMN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible obtener los datos desde el servidor de datos..
        /// </summary>
        public static string DB_RECOVERY {
            get {
                return ResourceManager.GetString("DB_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------- DEBUG INFO  --------------------
        ///{0}.
        /// </summary>
        public static string DEBUG_MSG {
            get {
                return ResourceManager.GetString("DEBUG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CRITICO: No se ha definido el esquema de datos por defecto.
        /// </summary>
        public static string DEFAULT_SCHEMA_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEFAULT_SCHEMA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} no es válido. Existe otro registro con el mismo código..
        /// </summary>
        public static string DUPLICATE_CODE {
            get {
                return ResourceManager.GetString("DUPLICATE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno de los registros insertados provocaría valores duplicados en la tabla..
        /// </summary>
        public static string DUPLICATE_KEY {
            get {
                return ResourceManager.GetString("DUPLICATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este email no está disponible.
        /// </summary>
        public static string EMAIL_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("EMAIL_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el campo {0} en la consulta ejecutada..
        /// </summary>
        public static string FIELD_NOT_FOUND {
            get {
                return ResourceManager.GetString("FIELD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga completada. A continuación se procederá a la actualización de la aplicación..
        /// </summary>
        public static string FTP_200 {
            get {
                return ResourceManager.GetString("FTP_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen actualizaciones disponibles..
        /// </summary>
        public static string FTP_550 {
            get {
                return ResourceManager.GetString("FTP_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la conexión al servidor FTP..
        /// </summary>
        public static string FTP_GENERICO {
            get {
                return ResourceManager.GetString("FTP_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha definido mensaje de error asociado para el código de error &quot;{0}&quot; devuelto por nHibernate..
        /// </summary>
        public static string GENERIC_ADO {
            get {
                return ResourceManager.GetString("GENERIC_ADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en los datos del formulario.
        ///
        ///Los campos marcados con * necesitan un valor..
        /// </summary>
        public static string GENERIC_VALIDATION_FAIL {
            get {
                return ResourceManager.GetString("GENERIC_VALIDATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción informativa.
        /// </summary>
        public static string INFO_EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("INFO_EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al insertar el objeto con ID = {1} del tipo {0}.
        /// </summary>
        public static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código {0} tiene un formato no válido. Debe ser un número..
        /// </summary>
        public static string INVALID_CODE {
            get {
                return ResourceManager.GetString("INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;{0}&quot; contiene datos no válidos..
        /// </summary>
        public static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de sesión no válido..
        /// </summary>
        public static string INVALID_SESSION_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_SESSION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento no encontrado.
        /// </summary>
        public static string ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible acceder en modo escritura al elemento seleccionado.
        ///Otro usuario está modificándolo en este momento..
        /// </summary>
        public static string LOCKED_ROW {
            get {
                return ResourceManager.GetString("LOCKED_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION: {0}
        ///MORE INFO: {1}.
        /// </summary>
        public static string LOG_MESSAGE {
            get {
                return ResourceManager.GetString("LOG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al iniciar sesión. Por favor, inténtelo pasados unos minutos. Si el error persiste póngase en contacto con el servicio de atención al cliente..
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos. Asegúrate de que has escrito bien tus datos de acceso y que no tienes el bloqueo de mayúsculas activado..
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado ninguna versión de Crystal Reports instalada en su equipo. Esto provocará un error en las funciones de impresión y exportación a PDF..
        /// </summary>
        public static string NO_CRYSTAL_REPORTS {
            get {
                return ResourceManager.GetString("NO_CRYSTAL_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible finalizar con éxito la operación.
        ///.
        /// </summary>
        public static string NO_OPERATION {
            get {
                return ResourceManager.GetString("NO_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la entrada de registro {0}. Esto impide gestionar las imágenes y otros recursos compartidos. Por favor, cree la entrada del registro para indicar a la aplicación donde se encuentra instalada la versión de {1} que actúa de servidor..
        /// </summary>
        public static string NO_SERVER_PATH {
            get {
                return ResourceManager.GetString("NO_SERVER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena de conexión a la base de datos no contiene el parámetro &quot;{0}&quot;.
        /// </summary>
        public static string NOT_FOUND_CONNECTION_PARAM {
            get {
                return ResourceManager.GetString("NOT_FOUND_CONNECTION_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al inicializar {0}.
        /// </summary>
        public static string OFFICE_INIT {
            get {
                return ResourceManager.GetString("OFFICE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado una versión válida de {0} instalado en el sistema.
        /// </summary>
        public static string OFFICE_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("OFFICE_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción no permitida.
        /// </summary>
        public static string OPERATION_NOT_VALID {
            get {
                return ResourceManager.GetString("OPERATION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Párametro {0} de tipo inválido. Tipo {1} esperado..
        /// </summary>
        public static string PARAMETER_INVALID_TYPE {
            get {
                return ResourceManager.GetString("PARAMETER_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro {0} no se ha encontrado.
        /// </summary>
        public static string PARAMETER_NOT_FOUND {
            get {
                return ResourceManager.GetString("PARAMETER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las códigos pin no coinciden.
        /// </summary>
        public static string PIN_NOT_MATCH {
            get {
                return ResourceManager.GetString("PIN_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenta acceder a la clase PrincipalBase sin haberla incializado previamente.
        /// </summary>
        public static string PRINCIPALBASE_NOT_INICIALIZATED {
            get {
                return ResourceManager.GetString("PRINCIPALBASE_NOT_INICIALIZATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la entrada de registro de Windows &apos;{0}&apos;.
        /// </summary>
        public static string REG32_ENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("REG32_ENTRY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRY KEY &apos;{0}&apos; FOUND.
        /// </summary>
        public static string REG32_KEY_FOUND {
            get {
                return ResourceManager.GetString("REG32_KEY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRY KEY &apos;{0}&apos; NOT FOUND.
        /// </summary>
        public static string REG32_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("REG32_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la entrada de registro de PostgreSQL para la versión {0}.
        /// </summary>
        public static string REG32_POSTGRE_VERSION_ENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("REG32_POSTGRE_VERSION_ENTRY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la aplicación de restauración de copias de seguridad..
        /// </summary>
        public static string RESTORE_APP_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESTORE_APP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha detectado una variable con valor nulo. Revise las reglas de validación de propiedades del objeto..
        /// </summary>
        public static string RULES_CHECK {
            get {
                return ResourceManager.GetString("RULES_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CRITICO: No se ha encontrado el esquema de datos {0}.
        /// </summary>
        public static string SCHEMA_NOT_FOUND {
            get {
                return ResourceManager.GetString("SCHEMA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible conectar con el servidor de datos. Es posible que haya problemas de conectividad en su equipo o que el servidor no esté disponible..
        /// </summary>
        public static string SERVER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión nº {0} del tipo {1} no existe.
        /// </summary>
        public static string SESSION_EXCEPTION {
            get {
                return ResourceManager.GetString("SESSION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise los datos de configuración del servidor SMTP en Opciones.
        /// </summary>
        public static string SMTP_SETTINGS {
            get {
                return ResourceManager.GetString("SMTP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible borrar un usario SUPERUSER.
        /// </summary>
        public static string SUPERUSER_DELETE {
            get {
                return ResourceManager.GetString("SUPERUSER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de sintaxis en la consulta SQL.
        ///QUERY: {0}.
        /// </summary>
        public static string SYNTAX_ERROR {
            get {
                return ResourceManager.GetString("SYNTAX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tabla o alias contenida en la sentencia no existe en la base de datos.
        /// </summary>
        public static string UNDEFINED_TABLE {
            get {
                return ResourceManager.GetString("UNDEFINED_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar el objeto con OID = {1} del tipo {0}.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado ningún fichero de actualización.
        /// </summary>
        public static string UPDATE_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("UPDATE_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario {0} no autorizado. Su usuario ha sido bloqueado. 
        ///Contacte con el administrador..
        /// </summary>
        public static string USER_LOCKED {
            get {
                return ResourceManager.GetString("USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible acceder al sistema con este usuario. El usuario {0} ha iniciado una sesión en el sistema previamente..
        /// </summary>
        public static string USER_LOGGED {
            get {
                return ResourceManager.GetString("USER_LOGGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nombre de usuario no está disponible.
        /// </summary>
        public static string USERNAME_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("USERNAME_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del campo {0} no es válido.
        /// </summary>
        public static string VALIDATION_FAIL {
            get {
                return ResourceManager.GetString("VALIDATION_FAIL", resourceCulture);
            }
        }
    }
}
