//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está permitido realizar esa acción..
        /// </summary>
        public static string ACTION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ACTION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string AVISO_CAPTION {
            get {
                return ResourceManager.GetString("AVISO_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password modificado.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código PIN modificado.
        /// </summary>
        public static string CHANGE_PIN_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para insertar o actualizar objetos hijo debe utilizar las funciones Insert o Update..
        /// </summary>
        public static string CHILD_SAVE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("CHILD_SAVE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error intentando cerrar una sesión..
        /// </summary>
        public static string CLOSE_SESSION_ERROR {
            get {
                return ResourceManager.GetString("CLOSE_SESSION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen conexiones abiertas desde las diferentes direcciones:.
        /// </summary>
        public static string CLOSE_SESSIONS_1 {
            get {
                return ResourceManager.GetString("CLOSE_SESSIONS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si continúa, las conexiones existentes se cerrarán perdiendo toda la información.
        ///¿Desea cerrarlas antes de continuar?.
        /// </summary>
        public static string CLOSE_SESSIONS_2 {
            get {
                return ResourceManager.GetString("CLOSE_SESSIONS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la propiedad &quot;{0}&quot; en el tipo &quot;{1}&quot;.
        /// </summary>
        public static string COLUMN_NOT_FOUND {
            get {
                return ResourceManager.GetString("COLUMN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos guardados con éxito.
        /// </summary>
        public static string DATA_SAVED {
            get {
                return ResourceManager.GetString("DATA_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versión instalada de la base de datos ({0}) para {2} es superior a la versión requerida por la aplicación ({1}). Es necesario actualizar la aplicación a una versión compatible..
        /// </summary>
        public static string DB_VERSION_HIGHER {
            get {
                return ResourceManager.GetString("DB_VERSION_HIGHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versión instalada de la base de datos ({0}) para {2} es inferior a la versión requerida por la aplicación ({1}). Es necesario actualizar la base de datos a una versión compatible..
        /// </summary>
        public static string DB_VERSION_LOWER {
            get {
                return ResourceManager.GetString("DB_VERSION_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la eliminación del elemento seleccionado?.
        /// </summary>
        public static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está permitido eliminar el usuario {0}.
        /// </summary>
        public static string DELETE_USER_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("DELETE_USER_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se va a proceder al cálculo de las bases de cálculo y cotización de los empleados de alta en la empresa.
        ///
        ///                                              ¿Desea continuar con el proceso?.
        /// </summary>
        public static string DO_HISTORICO {
            get {
                return ResourceManager.GetString("DO_HISTORICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise que no haya códigos duplicados..
        /// </summary>
        public static string DUAL_CODE {
            get {
                return ResourceManager.GetString("DUAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro elemento con ese códígo..
        /// </summary>
        public static string DUPLICATED_CODE {
            get {
                return ResourceManager.GetString("DUPLICATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está permitido editar el usuario {0}.
        /// </summary>
        public static string EDIT_USER_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("EDIT_USER_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el campo {0} en la consulta ejecutada..
        /// </summary>
        public static string FIELD_NOT_FOUND {
            get {
                return ResourceManager.GetString("FIELD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en los datos del formulario.
        ///
        ///Los campos marcados con * necesitan un valor..
        /// </summary>
        public static string GENERIC_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración de la clase no define el método heredado: {0}.
        /// </summary>
        public static string IMP_EXCEPTION {
            get {
                return ResourceManager.GetString("IMP_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de sesión no válido..
        /// </summary>
        public static string INVALID_SESSION_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_SESSION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos....
        /// </summary>
        public static string LOADING_DATA {
            get {
                return ResourceManager.GetString("LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incializando esquema de datos....
        /// </summary>
        public static string LOADING_DATA_SCHEMA {
            get {
                return ResourceManager.GetString("LOADING_DATA_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible bloquear el elemento seleccionado.
        ///Otro usuario está modificándolo en este momento. .
        /// </summary>
        public static string LOCK_ERROR {
            get {
                return ResourceManager.GetString("LOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG STARTED {0}.
        /// </summary>
        public static string LOG_STARTED {
            get {
                return ResourceManager.GetString("LOG_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no cumple los requisitos de entrada..
        /// </summary>
        public static string MASK_INPUT_REJECTED {
            get {
                return ResourceManager.GetString("MASK_INPUT_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Usuario.
        /// </summary>
        public static string NEW_USER {
            get {
                return ResourceManager.GetString("NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No procede la copia. Ultima copia realizada el {0}
        ///
        ///Para modificar las opciones de configuración de copias de seguridad acceda al formulario de opciones de la aplicacion..
        /// </summary>
        public static string NO_BACKUP_POLICY {
            get {
                return ResourceManager.GetString("NO_BACKUP_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha inicializado el criterio de consulta..
        /// </summary>
        public static string NO_CRITERIA {
            get {
                return ResourceManager.GetString("NO_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha indicado un valor para  &apos;{0}&apos;.
        /// </summary>
        public static string NO_FIELD_FILLED {
            get {
                return ResourceManager.GetString("NO_FIELD_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado un valor para &apos;{0}&apos;.
        /// </summary>
        public static string NO_FIELD_SELECTED {
            get {
                return ResourceManager.GetString("NO_FIELD_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar un Código válido.
        /// </summary>
        public static string NO_ID_SELECTED {
            get {
                return ResourceManager.GetString("NO_ID_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha indicado un valor para el campo Nombre.
        /// </summary>
        public static string NO_NAME_SELECTED {
            get {
                return ResourceManager.GetString("NO_NAME_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo debe contener un valor no nulo..
        /// </summary>
        public static string NO_NULL_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("NO_NULL_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha indicado un valor para el campo Password.
        /// </summary>
        public static string NO_PASSWORD_SELECTED {
            get {
                return ResourceManager.GetString("NO_PASSWORD_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado elementos coincidentes.
        /// </summary>
        public static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha introducido ningún valor para el campo &apos;{0}&apos;.
        /// </summary>
        public static string NO_VALUE_SELECTED {
            get {
                return ResourceManager.GetString("NO_VALUE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El uso del método {0} no está permitido para este objeto.
        /// </summary>
        public static string NOR_ALLOWED_CODE_EXCEPTION {
            get {
                return ResourceManager.GetString("NOR_ALLOWED_CODE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena de conexión a la base de datos no contiene el parámetro &quot;{0}&quot;.
        /// </summary>
        public static string NOT_FOUND_CONNECTION_PARAM {
            get {
                return ResourceManager.GetString("NOT_FOUND_CONNECTION_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han definido los parámetros de acceso al servidor FTP. Debe sobrecargar las propiedades necesarias de PrincipalBase en su fichero Principal.
        /// </summary>
        public static string NOT_FTP_PARAMS {
            get {
                return ResourceManager.GetString("NOT_FTP_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización realizada con éxito.
        /// </summary>
        public static string OK_UPDATE {
            get {
                return ResourceManager.GetString("OK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código pin debe ser un número de 4 dígitos.
        /// </summary>
        public static string PIN_CODE_VALIDATION {
            get {
                return ResourceManager.GetString("PIN_CODE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está permitido el uso de esta función Remove. Utilice en su lugar la sobrecarga en que el objeto padre es un parámetro..
        /// </summary>
        public static string REMOVE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("REMOVE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para acceder a esta esquema.
        /// </summary>
        public static string SCHEMA_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SCHEMA_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha establecido un nombre para el elemento seguro..
        /// </summary>
        public static string SECURE_ITEM_NAME_EMPTY {
            get {
                return ResourceManager.GetString("SECURE_ITEM_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha establecido un tipo para el elemento seguro..
        /// </summary>
        public static string SECURE_ITEM_TIPO_NULL {
            get {
                return ResourceManager.GetString("SECURE_ITEM_TIPO_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión nº {0} del tipo {1} no existe.
        /// </summary>
        public static string SESSION_EXCEPTION {
            get {
                return ResourceManager.GetString("SESSION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS no enviado.
        /// </summary>
        public static string SMS_SENT_ERROR {
            get {
                return ResourceManager.GetString("SMS_SENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS enviado con éxito.
        /// </summary>
        public static string SMS_SENT_OK {
            get {
                return ResourceManager.GetString("SMS_SENT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario y la contraseña no pueden contener espacios en blanco..
        /// </summary>
        public static string SQL_INYECTION {
            get {
                return ResourceManager.GetString("SQL_INYECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario borrado.
        /// </summary>
        public static string USER_DELETED {
            get {
                return ResourceManager.GetString("USER_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado a realizar esta operación.
        /// </summary>
        public static string USER_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("USER_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autentificado.
        ///Compruebe su nombre de usuario y contraseña..
        /// </summary>
        public static string USER_NOT_AUTHENTIFICATED {
            get {
                return ResourceManager.GetString("USER_NOT_AUTHENTIFICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando permisos....
        /// </summary>
        public static string USER_VALIDATION_MSG {
            get {
                return ResourceManager.GetString("USER_VALIDATION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectando con el servidor y validando al usuario....
        /// </summary>
        public static string VALIDATING_USER {
            get {
                return ResourceManager.GetString("VALIDATING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKING.
        /// </summary>
        public static string WORKING {
            get {
                return ResourceManager.GetString("WORKING", resourceCulture);
            }
        }
    }
}
