//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\.
        /// </summary>
        public static string APP_REG32 {
            get {
                return ResourceManager.GetString("APP_REG32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Backups\.
        /// </summary>
        public static string BACKUPS {
            get {
                return ResourceManager.GetString("BACKUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP BusinessObjects\Crystal Reports for .NET Framework 4.0.
        /// </summary>
        public static string CRYSTAL_REPORTS_KEY {
            get {
                return ResourceManager.GetString("CRYSTAL_REPORTS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DATA_PATH {
            get {
                return ResourceManager.GetString("DATA_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string DLL_FILES_PATH {
            get {
                return ResourceManager.GetString("DLL_FILES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asm\.
        /// </summary>
        public static string NH_CONFIG_FILES {
            get {
                return ResourceManager.GetString("NH_CONFIG_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hibernate.cfg.xml.
        /// </summary>
        public static string NH_MAIN_CONFIG_FILE {
            get {
                return ResourceManager.GetString("NH_MAIN_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hibernate-{0}.cfg.xml.
        /// </summary>
        public static string NH_SCHEMA_CONFIG_FILE {
            get {
                return ResourceManager.GetString("NH_SCHEMA_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asm\.
        /// </summary>
        public static string NH_SERVICES_CONFIG_FILES {
            get {
                return ResourceManager.GetString("NH_SERVICES_CONFIG_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft\Office\{0}\{1}\InstallRoot.
        /// </summary>
        public static string OFFICE_REG32_W7 {
            get {
                return ResourceManager.GetString("OFFICE_REG32_W7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow6432Node\Microsoft\Office\{0}\{1}\InstallRoot.
        /// </summary>
        public static string OFFICE_REG32_WS2008 {
            get {
                return ResourceManager.GetString("OFFICE_REG32_WS2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \bin\serverctl.vbs.
        /// </summary>
        public static string PG_CTL {
            get {
                return ResourceManager.GetString("PG_CTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \bin\pg_dump.exe.
        /// </summary>
        public static string PG_DUMP {
            get {
                return ResourceManager.GetString("PG_DUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \postgresql\pgpass.conf.
        /// </summary>
        public static string PG_PASS {
            get {
                return ResourceManager.GetString("PG_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SQL\pg_restore.exe.
        /// </summary>
        public static string PG_RESTORE {
            get {
                return ResourceManager.GetString("PG_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL\Installations\.
        /// </summary>
        public static string POSTGRESQL_WINREG_32 {
            get {
                return ResourceManager.GetString("POSTGRESQL_WINREG_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow6432Node\PostgreSQL\Installations\.
        /// </summary>
        public static string POSTGRESQL_WINREG_6432 {
            get {
                return ResourceManager.GetString("POSTGRESQL_WINREG_6432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerPath.
        /// </summary>
        public static string SERVER_PATH_KEY {
            get {
                return ResourceManager.GetString("SERVER_PATH_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string SERVICES_DLL_FILES_PATH {
            get {
                return ResourceManager.GetString("SERVICES_DLL_FILES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string USERS_PATH {
            get {
                return ResourceManager.GetString("USERS_PATH", resourceCulture);
            }
        }
    }
}
