//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.WebFace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.WebFace.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción {0} no encontrada en el controlador {1}.
        /// </summary>
        public static string ACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema nos ha informado del problema y estamos trabajando para solucionarlo.
        /// </summary>
        public static string ERROR_000 {
            get {
                return ResourceManager.GetString("ERROR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error del sistema.
        /// </summary>
        public static string ERROR_000_TITLE {
            get {
                return ResourceManager.GetString("ERROR_000_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido una petición errónea. Revise los datos de la petición..
        /// </summary>
        public static string ERROR_400 {
            get {
                return ResourceManager.GetString("ERROR_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petición errónea.
        /// </summary>
        public static string ERROR_400_TITLE {
            get {
                return ResourceManager.GetString("ERROR_400_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario ser un usuario autentificado para realizar la acción solicitada. Inicie sesión e inténtelo de nuevo..
        /// </summary>
        public static string ERROR_401 {
            get {
                return ResourceManager.GetString("ERROR_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autorizado. Necesita proporcionar credenciales.
        /// </summary>
        public static string ERROR_401_TITLE {
            get {
                return ResourceManager.GetString("ERROR_401_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para realizar esta acción. Si necesita acceso a este servicio contacte con el servicio de soporte..
        /// </summary>
        public static string ERROR_403 {
            get {
                return ResourceManager.GetString("ERROR_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No autorizado. No tiene permisos para realizar esta acción.
        /// </summary>
        public static string ERROR_403_TITLE {
            get {
                return ResourceManager.GetString("ERROR_403_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra la página solicitada. El sistema nos ha informado del problema y revisaremos la petición por si fuera un error de la aplicación..
        /// </summary>
        public static string ERROR_404 {
            get {
                return ResourceManager.GetString("ERROR_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página no encontrada.
        /// </summary>
        public static string ERROR_404_TITLE {
            get {
                return ResourceManager.GetString("ERROR_404_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturada una excepción nula.
        /// </summary>
        public static string NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} debe tener al menos {2} caracteres.
        /// </summary>
        public static string PASSWORD_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connectivity is lost. 
        ///Please try again later.
        ///We apologise for the inconvenience.
        ///
        ///Error: {0}.
        /// </summary>
        public static string SERVER_CONNECTION {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la vista {0}.
        /// </summary>
        public static string VIEW_TEMPLATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("VIEW_TEMPLATE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
