//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.WebFace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.WebFace.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string ACTION_APPLY {
            get {
                return ResourceManager.GetString("ACTION_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        public static string ACTION_BACK {
            get {
                return ResourceManager.GetString("ACTION_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string ACTION_CLOSE {
            get {
                return ResourceManager.GetString("ACTION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ACTION_CREATE {
            get {
                return ResourceManager.GetString("ACTION_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ACTION_DELETE {
            get {
                return ResourceManager.GetString("ACTION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ACTION_DETAILS {
            get {
                return ResourceManager.GetString("ACTION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string ACTION_LOGIN {
            get {
                return ResourceManager.GetString("ACTION_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ACTION_OK {
            get {
                return ResourceManager.GetString("ACTION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string ACTION_PRINT {
            get {
                return ResourceManager.GetString("ACTION_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string ACTION_REGISTER {
            get {
                return ResourceManager.GetString("ACTION_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ACTION_SAVE {
            get {
                return ResourceManager.GetString("ACTION_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string ACTION_SEARCH {
            get {
                return ResourceManager.GetString("ACTION_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ACTION_UPDATE {
            get {
                return ResourceManager.GetString("ACTION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string ADMIN_GROUP_TITLE {
            get {
                return ResourceManager.GetString("ADMIN_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cualquier columna.
        /// </summary>
        public static string ANY_FIELD {
            get {
                return ResourceManager.GetString("ANY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string CHANGE_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Pin.
        /// </summary>
        public static string CHANGE_PIN_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_PIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención al Cliente.
        /// </summary>
        public static string CLIENTS_GROUP_TITLE {
            get {
                return ResourceManager.GetString("CLIENTS_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string CONTACTS {
            get {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Error.
        /// </summary>
        public static string ERROR_CODE {
            get {
                return ResourceManager.GetString("ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada.
        /// </summary>
        public static string EVERY {
            get {
                return ResourceManager.GetString("EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string GENERAL_DATA {
            get {
                return ResourceManager.GetString("GENERAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string HOUR {
            get {
                return ResourceManager.GetString("HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string ID_GROUP_TITLE {
            get {
                return ResourceManager.GetString("ID_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localización y Contacto.
        /// </summary>
        public static string LOCATION_GROUP_TITLE {
            get {
                return ResourceManager.GetString("LOCATION_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás registrado como .
        /// </summary>
        public static string LOGGED_AS {
            get {
                return ResourceManager.GetString("LOGGED_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        public static string MAIN_DATA {
            get {
                return ResourceManager.GetString("MAIN_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de cuenta.
        /// </summary>
        public static string MANAGE_ACCOUNT_TITLE {
            get {
                return ResourceManager.GetString("MANAGE_ACCOUNT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string MOBILE_PHONE {
            get {
                return ResourceManager.GetString("MOBILE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string PROFILE_GROUP_TITLE {
            get {
                return ResourceManager.GetString("PROFILE_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buscar.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string SMS_GATEWAY_ACCOUNT {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string SMS_GATEWAY_CODE {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela de SMS .
        /// </summary>
        public static string SMS_GATEWAY_GROUP_TITLE {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string SMS_GATEWAY_NAME {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SMS_GATEWAY_PWD {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string SMS_GATEWAY_USER {
            get {
                return ResourceManager.GetString("SMS_GATEWAY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string SMTP_EMAIL {
            get {
                return ResourceManager.GetString("SMTP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar SSL.
        /// </summary>
        public static string SMTP_ENABLE_SSL {
            get {
                return ResourceManager.GetString("SMTP_ENABLE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        public static string SMTP_GROUP_TITLE {
            get {
                return ResourceManager.GetString("SMTP_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SMTP_HOST {
            get {
                return ResourceManager.GetString("SMTP_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto.
        /// </summary>
        public static string SMTP_PORT {
            get {
                return ResourceManager.GetString("SMTP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SMTP_PWD {
            get {
                return ResourceManager.GetString("SMTP_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string SMTP_USER {
            get {
                return ResourceManager.GetString("SMTP_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error con su petición.
        /// </summary>
        public static string SUBTITLE_ERROR {
            get {
                return ResourceManager.GetString("SUBTITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superusuario.
        /// </summary>
        public static string SUPER_USER {
            get {
                return ResourceManager.GetString("SUPER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte Técnico.
        /// </summary>
        public static string SUPPORT_GROUP_TITLE {
            get {
                return ResourceManager.GetString("SUPPORT_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso al Sistema.
        /// </summary>
        public static string SYSTEM_ACCESS {
            get {
                return ResourceManager.GetString("SYSTEM_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje del Sistema.
        /// </summary>
        public static string SYSTEM_MESSAGE {
            get {
                return ResourceManager.GetString("SYSTEM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear {0}.
        /// </summary>
        public static string TITLE_CREATE {
            get {
                return ResourceManager.GetString("TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar {0}.
        /// </summary>
        public static string TITLE_DELETE {
            get {
                return ResourceManager.GetString("TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de {0}.
        /// </summary>
        public static string TITLE_DETAILS {
            get {
                return ResourceManager.GetString("TITLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upssss... ¡¡Lo sentimos!!.
        /// </summary>
        public static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar {0}.
        /// </summary>
        public static string TITLE_UPDATE {
            get {
                return ResourceManager.GetString("TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Acceso.
        /// </summary>
        public static string USER_ACCESS_DATA {
            get {
                return ResourceManager.GetString("USER_ACCESS_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación.
        /// </summary>
        public static string USER_DOCUMENTATION {
            get {
                return ResourceManager.GetString("USER_DOCUMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string USER_LIST {
            get {
                return ResourceManager.GetString("USER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Personales.
        /// </summary>
        public static string USER_PERSONAL_DATA {
            get {
                return ResourceManager.GetString("USER_PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de Usuario.
        /// </summary>
        public static string USER_PROFILE {
            get {
                return ResourceManager.GetString("USER_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de Usuarios.
        /// </summary>
        public static string USERS_CONTROL {
            get {
                return ResourceManager.GetString("USERS_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        public static string WEEK {
            get {
                return ResourceManager.GetString("WEEK", resourceCulture);
            }
        }
    }
}
