//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Example.Qapture.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Example.Qapture.App_GlobalResources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ACTION_CANCEL {
            get {
                return ResourceManager.GetString("ACTION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string ACTION_CAPTURE {
            get {
                return ResourceManager.GetString("ACTION_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ACTION_CLOSE {
            get {
                return ResourceManager.GetString("ACTION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string ACTION_RETRY {
            get {
                return ResourceManager.GetString("ACTION_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string ACTION_SCAN {
            get {
                return ResourceManager.GetString("ACTION_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &amp; Upload.
        /// </summary>
        public static string ACTION_SCAN_AND_SAVE {
            get {
                return ResourceManager.GetString("ACTION_SCAN_AND_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ACTION_UPLOAD {
            get {
                return ResourceManager.GetString("ACTION_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Scan &amp; Show&quot; Example.
        /// </summary>
        public static string BASIC_EXAMPLE {
            get {
                return ResourceManager.GetString("BASIC_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT_TITLE {
            get {
                return ResourceManager.GetString("CONTACT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string FAIL_UPLOAD {
            get {
                return ResourceManager.GetString("FAIL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install &lt;i&gt;Qapture&lt;/i&gt; and use your own scanner from the web.
        /// </summary>
        public static string HOW_TO_INSTALL_PLUGIN_SUBTITLE {
            get {
                return ResourceManager.GetString("HOW_TO_INSTALL_PLUGIN_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Side: How to install the &lt;/&gt;Qapture&lt;/i&gt; plug-in.
        /// </summary>
        public static string HOW_TO_INSTALL_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("HOW_TO_INSTALL_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate &lt;i&gt;Qapture&lt;/i&gt; plug-in and allow your application to use  a client side scanner.
        /// </summary>
        public static string HOW_TO_USE_PLUGIN_SUBTITLE {
            get {
                return ResourceManager.GetString("HOW_TO_USE_PLUGIN_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &lt;i&gt;Qapture&lt;/i&gt; plug-in to scan and upload the image.
        /// </summary>
        public static string HOW_TO_USE_PLUGIN_SUBTITLE_UPLOAD {
            get {
                return ResourceManager.GetString("HOW_TO_USE_PLUGIN_SUBTITLE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Side: How to use the &lt;i&gt;Qapture&lt;/i&gt; plug-in.
        /// </summary>
        public static string HOW_TO_USE_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("HOW_TO_USE_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Side: How to use the &lt;i&gt;Qapture&lt;/i&gt; plug-in. (Upload to server).
        /// </summary>
        public static string HOW_TO_USE_PLUGIN_TITLE_UPLOAD {
            get {
                return ResourceManager.GetString("HOW_TO_USE_PLUGIN_TITLE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PHOTO {
            get {
                return ResourceManager.GetString("PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bottom layer contains the &lt;i&gt;Qapture&lt;/i&gt; object.
        /// </summary>
        public static string QAPTURE_LAYER_TEXT {
            get {
                return ResourceManager.GetString("QAPTURE_LAYER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned image.
        /// </summary>
        public static string SCAN_IMAGE_NAME {
            get {
                return ResourceManager.GetString("SCAN_IMAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {file} is too large, maximum file size is {sizeLimit}..
        /// </summary>
        public static string SIZE_ERROR {
            get {
                return ResourceManager.GetString("SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning, plug-in, cabinets and more....
        /// </summary>
        public static string TUTORIALS_SUBTITLE {
            get {
                return ResourceManager.GetString("TUTORIALS_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string TUTORIALS_TITLE {
            get {
                return ResourceManager.GetString("TUTORIALS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {file} has an invalid extension. Valid extension(s): {extensions}..
        /// </summary>
        public static string TYPE_ERROR {
            get {
                return ResourceManager.GetString("TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Scan &amp; Upload&quot; Example.
        /// </summary>
        public static string UPLOAD_EXAMPLE {
            get {
                return ResourceManager.GetString("UPLOAD_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning. Please wait....
        /// </summary>
        public static string WAITING {
            get {
                return ResourceManager.GetString("WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string WAITING_RESPONSE {
            get {
                return ResourceManager.GetString("WAITING_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string WAITING_UPLOAD_RESPONSE {
            get {
                return ResourceManager.GetString("WAITING_UPLOAD_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
    }
}
