/* UPDATE 4.11.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '4.11.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

INSERT INTO "UserSetting" ("OID_USER", "NAME", "VALUE") (SELECT U."OID", 'DEFAULT_N_COPIES', '1' FROM "User" AS U);

SET SEARCH_PATH = "0001";




