/* UPDATE 4.10.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '4.10.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

ALTER TABLE "User" RENAME COLUMN "DEFAULT_SCHEMA" TO "ESTADO";
UPDATE "User" SET "ESTADO" = 4;

SET SEARCH_PATH = "0001";




