/* UPDATE 5.4.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '5.4.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

CREATE TABLE "Setting"
(
	"OID" bigserial NOT NULL UNIQUE,
	"NAME" character varying(255) NOT NULL,
    "COPY" boolean DEFAULT TRUE,
    "COMMENTS" character varying,
	CONSTRAINT "Setting_PK" PRIMARY KEY ("OID")
) WITHOUT OIDS;

ALTER TABLE "Setting" OWNER TO moladmin;
GRANT ALL ON TABLE "Setting" TO GROUP "MOLEQULE_ADMINISTRATOR";

ALTER TABLE "UserSetting" ADD COLUMN "OID_SETTING" int8 DEFAULT 0;

INSERT INTO "Setting" ("NAME", "COPY") VALUES ('FILES_HOST', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('PDF_PRINTS_FOLDER', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_HOST', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_PORT', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_SCHEMA', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_USER', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_EMAIL', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_PWD', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_ENABLE_SSL', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_FACTURAS_RECIBIDAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_FACTURAS_EMITIDAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_COBROS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PAGOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_GASTOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('ACTIVE_YEAR', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('CULTURE', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SALIDA_CONTABILIDAD_FOLDER', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_PAGOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_FACTURAS_RECIBIDAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_FACTURAS_EMITIDAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_COBROS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_GASTOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_SERIE_VENTA', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('FORMAT_GRIDS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_FACTURAS_EXPLOTACION', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_FACTURAS_ACREEDORES', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_OTROS_GASTOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_GASTOS_NOMINAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_EFECTOS_PENDIENTES_VTO', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_PAGOS_ESTIMADOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_FACTURAS_EMITIDAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_EXISTENCIAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_EFECTOS_NEGOCIADOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_EFECTOS_PENDIENTES', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_AYUDAS_PENDIENTES', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_AYUDAS_COBRADAS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('BALANCE_PRINT_BANCOS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SHOW_AUTOPILOT', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_SERIE_COMPRA', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_ALMACEN', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SHOW_NULL_RECORDS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_PRINTER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_TICKET_PRINTER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('USE_DEFAULT_PRINTER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_N_COPIES', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('USE_ACTIVE_YEAR', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('FOMENTO_FOLDER', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_AUDITORIAS', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('NOTIFY_PLAZO_AUDITORIAS', FALSE);

UPDATE "UserSetting" SET "OID_SETTING" = ST."OID"
FROM (SELECT "OID", "NAME" FROM "Setting") AS ST
WHERE "UserSetting"."NAME" = ST."NAME";

SET SEARCH_PATH = "0001";
