/* UPDATE 3.10.0.0*/

SET SEARCH_PATH = "COMMON";

CREATE TABLE "ItemMap"
(
  "OID" bigserial NOT NULL UNIQUE,
  "OID_ITEM" int8 NOT NULL,
  "PRIVILEGE" int8 NOT NULL,
  "OID_ASSOCIATE_ITEM" int8 NOT NULL,
  "ASSOCIATE_PRIVILEGE" int8 NOT NULL,
  CONSTRAINT "ITEMMAP_PK" PRIMARY KEY ("OID")
) WITHOUT OIDS;

ALTER TABLE "ItemMap" OWNER TO moladmin;
GRANT ALL ON TABLE "ItemMap" TO GROUP "MOLEQULE_ADMINISTRATOR";

SET SEARCH_PATH = "0001";


