/* UPDATE 4.8.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '4.8.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

INSERT INTO "COMMON"."Variable" ("NAME", "VALUE") VALUES ('APPLICATION_VERSION', '1.0.0.0');

SET SEARCH_PATH = "0001";




