/* UPDATE 4.9.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '4.9.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

INSERT INTO "UserSetting" ("OID_USER", "NAME", "VALUE") (SELECT U."OID", 'SHOW_NULL_RECORDS', 'TRUE' FROM "User" AS U);

SET SEARCH_PATH = "0001";




