/* UPDATE 6.3.4.2*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '6.3.4.2' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

ALTER TABLE "User" ADD COLUMN "ENTITY_TYPE" int8 DEFAULT 0;
UPDATE "User" SET "ENTITY_TYPE" = 7 WHERE "OID_CLIENT" != 0;
UPDATE "User" SET "ENTITY_TYPE" = 33 WHERE "OID_PARTNER" != 0;
UPDATE "User" SET "OID_CLIENT" = "OID_PARTNER" WHERE "OID_PARTNER" != 0;
ALTER TABLE "User" RENAME COLUMN "OID_CLIENT" TO "OID_ENTITY";
ALTER TABLE "User" DROP COLUMN "OID_PARTNER";
	
SET SEARCH_PATH = "0001";
