/* UPDATE 4.4.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '4.4.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

DROP TABLE IF EXISTS "UserSetting" CASCADE;
CREATE TABLE "UserSetting"
(
	"OID" bigserial NOT NULL,
	"OID_USER" bigint NOT NULL,
	"NAME" varchar(255) NOT NULL DEFAULT 0,
	"VALUE" varchar NOT NULL,
	CONSTRAINT "UserSetting_PK" PRIMARY KEY ("OID")
) WITHOUT OIDS;

ALTER TABLE "UserSetting" OWNER TO moladmin;
GRANT ALL ON TABLE "UserSetting" TO GROUP "MOLEQULE_ADMINISTRATOR";

ALTER TABLE "UserSetting" ADD FOREIGN KEY("OID_USER") REFERENCES "User" ("OID") ON UPDATE CASCADE ON DELETE CASCADE;

-- MOLEQULE SETTINGS
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('DEFAULT_SCHEMA', '01');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SHOW_AUTOPILOT', 'FALSE');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('FORMAT_GRIDS', 'TRUE');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('PDF_PRINTS_FOLDER', '');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('CULTURE', 'es-ES');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SMTP_HOST', '');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SMTP_PORT', '25');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SMTP_USER', '');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SMTP_PWD', '');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SMTP_EMAIL', '');

-- COMMON SETTINGS
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('USE_ACTIVE_YEAR', 'TRUE');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('ACTIVE_YEAR', '01/01/2012');

-- INVOICE SETTINGS
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('SALIDA_CONTABILIDAD_FOLDER', '');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('DEFAULT_SERIE_VENTA', '');

-- STORE SETTINGS
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('PLAZO_AVISO_VENCIMIENTO_PAGOS', '7');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('DEFAULT_SERIE_COMPRA', '');

INSERT INTO "UserSetting" ("OID_USER", "NAME", "VALUE") 
(SELECT U."OID", V."NAME", V."VALUE"
FROM "User" AS U, "Variable" AS V 
WHERE V."NAME" NOT LIKE '%DB_VERSION');

DELETE FROM "COMMON"."Variable" WHERE "NAME" NOT LIKE '%DB_VERSION';

INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('FILES_HOST', 'localhost');

SET SEARCH_PATH = "0001";

-- SCHEMA SETTINGS
--INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS', '1');


