/* UPDATE 5.1.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '5.1.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';

SET SEARCH_PATH = "0001";

INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_DAYS', '7');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_HOUR', '01/01/2012 00:00');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_LAST_DATE', '01/01/2012 00:00');



