/* UPDATE 5.0.0.0*/

SET SEARCH_PATH = "COMMON";

UPDATE "Variable" SET "VALUE" = '5.0.0.0' WHERE "NAME" = 'MOLEQULE_DB_VERSION';
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('POSTGRESQL_VERSION', '9.1.4.1');

SET SEARCH_PATH = "0001";




