//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Common.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        public static string CARGO_TITLE {
            get {
                return ResourceManager.GetString("CARGO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Bancarias {0}.
        /// </summary>
        public static string CUENTASBANCARIAS_TITLE {
            get {
                return ResourceManager.GetString("CUENTASBANCARIAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        public static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuntes Bancarios.
        /// </summary>
        public static string MOVIMIENTOS_TI {
            get {
                return ResourceManager.GetString("MOVIMIENTOS_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios.
        /// </summary>
        public static string MUNICIPIO_TITLE {
            get {
                return ResourceManager.GetString("MUNICIPIO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el país.
        /// </summary>
        public static string SELECT_COUNTRY_TITLE {
            get {
                return ResourceManager.GetString("SELECT_COUNTRY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una cuenta.
        /// </summary>
        public static string SELECT_CUENTA {
            get {
                return ResourceManager.GetString("SELECT_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la moneda.
        /// </summary>
        public static string SELECT_CURRENCY_TITLE {
            get {
                return ResourceManager.GetString("SELECT_CURRENCY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar email.
        /// </summary>
        public static string SEND_EMAIL {
            get {
                return ResourceManager.GetString("SEND_EMAIL", resourceCulture);
            }
        }
    }
}
