SET search_path TO "COMMON";
-- MOLEQULE COMMON DATA SCRIPT

-- INSERTS

INSERT INTO "User" ("SERIAL", "ID", "NAME", "PASSWORD", "ADMOR", "MAIN", "IS_PARTNER", "ESTADO", "PIN") VALUES (0, '000000', 'moladmin', 'fcabbe1bfb630c6e6a6c07d174275e45', TRUE, TRUE, FALSE, 10, '0000');
INSERT INTO "User" ("SERIAL", "ID", "NAME", "PASSWORD", "ADMOR", "MAIN", "IS_PARTNER", "ESTADO", "PIN") VALUES (1, '000001', 'Admin', 'fcabbe1bfb630c6e6a6c07d174275e45', FALSE, TRUE, FALSE, 10, '9999');
INSERT INTO "User" ("SERIAL", "ID", "NAME", "PASSWORD", "ADMOR", "MAIN", "IS_SERVICE", "ESTADO", "PIN") VALUES (2, '000002', 'molservice', 'fcabbe1bfb630c6e6a6c07d174275e45', FALSE, FALSE, TRUE, 10, '0000');

INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('MOLEQULE_DB_VERSION', '6.3.3.2');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('FILES_HOST', 'localhost');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('APPLICATION_VERSION', '1.0.0.0');
INSERT INTO "Variable" ("NAME", "VALUE") VALUES ('POSTGRESQL_VERSION', '9.1.4.1');

INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_SCHEMA', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SHOW_AUTOPILOT', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('FORMAT_GRIDS', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('PDF_PRINTS_FOLDER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('CULTURE', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_HOST', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_PORT', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_USER', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_PWD', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_EMAIL', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SMTP_ENABLE_SSL', FALSE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_PRINTER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('USE_DEFAULT_PRINTER', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('DEFAULT_N_COPIES', TRUE);
INSERT INTO "Setting" ("NAME", "COPY") VALUES ('SHOW_NULL_RECORDS', TRUE);

INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '01' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'DEFAULT_SCHEMA');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'FALSE' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SHOW_AUTOPILOT');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'TRUE' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'FORMAT_GRIDS');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'PDF_PRINTS_FOLDER');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'es-ES' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'CULTURE');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'localhost' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_HOST');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '25' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_PORT');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_USER');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_PWD');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_EMAIL');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'FALSE' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SMTP_ENABLE_SSL');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'DEFAULT_PRINTER');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'FALSE' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'USE_DEFAULT_PRINTER');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", '1' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'DEFAULT_N_COPIES');
INSERT INTO "UserSetting" ("OID_USER", "OID_SETTING", "NAME", "VALUE") (SELECT U."OID", S."OID", S."NAME", 'TRUE' FROM "User" AS U, "Setting" AS S WHERE S."NAME" = 'SHOW_NULL_RECORDS');

-- SECURE ITEMS INSERTS

INSERT INTO "SecureItem" ("NAME", "TIPO", "DESCRIPTOR") VALUES ('Variables', '000', 'VARIABLES');
