SET search_path TO "0001";
-- MOLEQULE SCHEMA DATA SCRIPT

-- USERS PRIVILEGES

INSERT INTO "Privilege" ("OID_USER", "OID_ITEM", "READ", "CREATE", "MODIFY", "DELETE") 
	SELECT u."OID", i."OID", FALSE, FALSE, FALSE, FALSE 
	FROM "COMMON"."User" AS u, "COMMON"."SecureItem" AS i
	WHERE (u."OID", i."OID") NOT IN (SELECT "OID_USER", "OID_ITEM" FROM "Privilege");
	
-- INSERTS

UPDATE "Privilege" SET "READ" = TRUE, "CREATE" = TRUE,"MODIFY" = TRUE,"DELETE" = TRUE WHERE "OID_USER" IN (SELECT "OID" FROM "COMMON"."User" WHERE "MAIN" = true);

INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('LINK_SEED', 'iQiQiQiQiQiQiQiQiQ');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_DAYS', '7');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_HOUR', '01/01/2012 00:00');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('BACKUPS_LAST_DATE', '01/01/2012 00:00');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('ADMIN_CONTACT', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('ADMIN_EMAIL', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('CLIENTS_CONTACT', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('CLIENTS_EMAIL', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SUPPORT_CONTACT', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SUPPORT_EMAIL', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('ADMIN_MOBILE_PHONE', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('CLIENTS_MOBILE_PHONE', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SUPPORT_MOBILE_PHONE', '');

INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_HOST', 'smtp.iqingenieros.com');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_PORT', '25');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_USER', 'iq_tech');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_PWD', 'iQi1998');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_EMAIL', 'tech@iqingenieros.com');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMTP_ENABLE_SSL', FALSE);

INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMS_GATEWAY_NAME', 'Esendex');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMS_GATEWAY_CODE', '1');	
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMS_GATEWAY_USER', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMS_GATEWAY_PWD', '');
INSERT INTO "Setting" ("NAME", "VALUE") VALUES ('SMS_GATEWAY_ACCOUNT', '');