//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.WebFace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("update")]
        public string API_ACTION_MONITOR {
            get {
                return ((string)(this["API_ACTION_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.alquilermotosporhora.com")]
        public string PRODUCTION_DOMAIN {
            get {
                return ((string)(this["PRODUCTION_DOMAIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("staging.alquilermotosporhora.com")]
        public string STAGING_DOMAIN {
            get {
                return ((string)(this["STAGING_DOMAIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("develop.alquilermotosporhora.com")]
        public string TEST_DOMAIN {
            get {
                return ((string)(this["TEST_DOMAIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("preproduction.alquilermotosporhora.com")]
        public string ALPHA_DOMAIN {
            get {
                return ((string)(this["ALPHA_DOMAIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("develop.alquilermotosporhora.com")]
        public string DEVELOPMENT_DOMAIN {
            get {
                return ((string)(this["DEVELOPMENT_DOMAIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string PROTOCOL {
            get {
                return ((string)(this["PROTOCOL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tW310AKKatOpvVb58FFHiBfFss0lft5u")]
        public string API_KEY {
            get {
                return ((string)(this["API_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7D8IXAKpQXhfUvejnwnhsJtDrGYO7Tm")]
        public string SECRET_KEY {
            get {
                return ((string)(this["SECRET_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/argos/monitor/")]
        public string API_URL_MONITOR {
            get {
                return ((string)(this["API_URL_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("monitor.html")]
        public string API_SERVICE_MONITOR {
            get {
                return ((string)(this["API_SERVICE_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("debug@iqingenieros.com;")]
        public string REPORT_DEBUG_EMAIL {
            get {
                return ((string)(this["REPORT_DEBUG_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support@iqingenieros.com;")]
        public string REPORT_SUPPORT_EMAIL {
            get {
                return ((string)(this["REPORT_SUPPORT_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("motorent@iqingenieros.com;josecelano@gmail.com")]
        public string REPORT_ADMIN_EMAIL {
            get {
                return ((string)(this["REPORT_ADMIN_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://checkip.dyndns.org")]
        public string PublicIPWebServicUrl {
            get {
                return ((string)(this["PublicIPWebServicUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gwaihir")]
        public string API_BASE_SUBDOMAIN {
            get {
                return ((string)(this["API_BASE_SUBDOMAIN"]));
            }
        }
    }
}
