//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal must be of type BusinessPrincipal, not.
        /// </summary>
        public static string BusinessPrincipalException {
            get {
                return ResourceManager.GetString("BusinessPrincipalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing an element is an invalid operation.
        /// </summary>
        public static string ChangeInvalidException {
            get {
                return ResourceManager.GetString("ChangeInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not directly mark a child object for deletion - use its parent collection.
        /// </summary>
        public static string ChildDeleteException {
            get {
                return ResourceManager.GetString("ChildDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear is an invalid operation.
        /// </summary>
        public static string ClearInvalidException {
            get {
                return ResourceManager.GetString("ClearInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_3166-1_List_en xml:lang=&quot;en&quot;&gt;
        ///	&lt;ISO_3166-1_Entry&gt;
        ///		&lt;ISO_3166-1_Country_name&gt;Afghanistan&lt;/ISO_3166-1_Country_name&gt;
        ///		&lt;ISO_3166-1_Alpha-2_Code_element&gt;AF&lt;/ISO_3166-1_Alpha-2_Code_element&gt;
        ///		&lt;Country_international_prefix&gt;93&lt;/Country_international_prefix&gt;
        ///	&lt;/ISO_3166-1_Entry&gt;
        ///	&lt;ISO_3166-1_Entry&gt;
        ///		&lt;ISO_3166-1_Country_name&gt;Aland Islands&lt;/ISO_3166-1_Country_name&gt;
        ///		&lt;ISO_3166-1_Alpha-2_Code_element&gt;AX&lt;/ISO_3166-1_Alpha-2_Code_element&gt;
        ///		&lt;Count [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - create not allowed.
        /// </summary>
        public static string CreateNotSupportedException {
            get {
                return ResourceManager.GetString("CreateNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - delete not allowed.
        /// </summary>
        public static string DeleteNotSupportedException {
            get {
                return ResourceManager.GetString("DeleteNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading value:.
        /// </summary>
        public static string ErrorReadingValueException {
            get {
                return ResourceManager.GetString("ErrorReadingValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - execute not allowed.
        /// </summary>
        public static string ExecuteNotSupportedException {
            get {
                return ResourceManager.GetString("ExecuteNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed on the server.
        /// </summary>
        public static string FailedOnServer {
            get {
                return ResourceManager.GetString("FailedOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - fetch not allowed.
        /// </summary>
        public static string FetchNotSupportedException {
            get {
                return ResourceManager.GetString("FetchNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business object must supply a non-null ID value in GetIdValue.
        /// </summary>
        public static string GetIdValueCantBeNull {
            get {
                return ResourceManager.GetString("GetIdValueCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert is an invalid operation.
        /// </summary>
        public static string InsertInvalidException {
            get {
                return ResourceManager.GetString("InsertInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - insert not allowed.
        /// </summary>
        public static string InsertNotSupportedException {
            get {
                return ResourceManager.GetString("InsertNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_4217 Pblshd=&quot;2014-01-01&quot;&gt;
        ///	&lt;CcyTbl&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;AFGHANISTAN&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Afghani&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;AFN&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;971&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ÅLAND ISLANDS&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Euro&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;EUR&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;978&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ALBANIA&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Lek&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;ALL&lt;/Ccy&gt;
        ///			&lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ISO_4217 {
            get {
                return ResourceManager.GetString("ISO_4217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lower case required.
        /// </summary>
        public static string LCaseStringRequiredRule {
            get {
                return ResourceManager.GetString("LCaseStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not exceed {1}.
        /// </summary>
        public static string MaxValueRule {
            get {
                return ResourceManager.GetString("MaxValueRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method call failed.
        /// </summary>
        public static string MethodCallFailed {
            get {
                return ResourceManager.GetString("MethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not implemented.
        /// </summary>
        public static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be less than {1}.
        /// </summary>
        public static string MinValueRule {
            get {
                return ResourceManager.GetString("MinValueRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyEdit is not valid on a child object.
        /// </summary>
        public static string NoApplyEditChildException {
            get {
                return ResourceManager.GetString("NoApplyEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginEdit is not valid on a child object.
        /// </summary>
        public static string NoBeginEditChildException {
            get {
                return ResourceManager.GetString("NoBeginEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelEdit is not valid on a child object.
        /// </summary>
        public static string NoCancelEditChildException {
            get {
                return ResourceManager.GetString("NoCancelEditChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid for root objects - use Delete instead.
        /// </summary>
        public static string NoDeleteRootException {
            get {
                return ResourceManager.GetString("NoDeleteRootException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nophoto {
            get {
                object obj = ResourceManager.GetObject("nophoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No principal object should be passed to DataPortal when using Windows integrated security.
        /// </summary>
        public static string NoPrincipalAllowedException {
            get {
                return ResourceManager.GetString("NoPrincipalAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not directly save a child object.
        /// </summary>
        public static string NoSaveChildException {
            get {
                return ResourceManager.GetString("NoSaveChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is still being edited and can not be saved.
        /// </summary>
        public static string NoSaveEditingException {
            get {
                return ResourceManager.GetString("NoSaveEditingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not valid and can not be saved.
        /// </summary>
        public static string NoSaveInvalidException {
            get {
                return ResourceManager.GetString("NoSaveInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such value exists:.
        /// </summary>
        public static string NoSuchValueExistsException {
            get {
                return ResourceManager.GetString("NoSuchValueExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must not be null.
        /// </summary>
        public static string NothingNotValid {
            get {
                return ResourceManager.GetString("NothingNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} number required.
        /// </summary>
        public static string NumberStringRequiredRule {
            get {
                return ResourceManager.GetString("NumberStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent value can only be set for child objects.
        /// </summary>
        public static string ParentSetException {
            get {
                return ResourceManager.GetString("ParentSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter must be a primitive type.
        /// </summary>
        public static string PrimitiveTypeRequired {
            get {
                return ResourceManager.GetString("PrimitiveTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property copy failed.
        /// </summary>
        public static string PropertyCopyFailed {
            get {
                return ResourceManager.GetString("PropertyCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property get not allowed.
        /// </summary>
        public static string PropertyGetNotAllowed {
            get {
                return ResourceManager.GetString("PropertyGetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property set not allowed.
        /// </summary>
        public static string PropertySetNotAllowed {
            get {
                return ResourceManager.GetString("PropertySetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match regular expression.
        /// </summary>
        public static string RegExMatchRule {
            get {
                return ResourceManager.GetString("RegExMatchRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove is an invalid operation.
        /// </summary>
        public static string RemoveInvalidException {
            get {
                return ResourceManager.GetString("RemoveInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string SmartDateT {
            get {
                return ResourceManager.GetString("SmartDateT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string SmartDateToday {
            get {
                return ResourceManager.GetString("SmartDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tom.
        /// </summary>
        public static string SmartDateTom {
            get {
                return ResourceManager.GetString("SmartDateTom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string SmartDateTomorrow {
            get {
                return ResourceManager.GetString("SmartDateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string SmartDateY {
            get {
                return ResourceManager.GetString("SmartDateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string SmartDateYesterday {
            get {
                return ResourceManager.GetString("SmartDateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not exceed {1} characters.
        /// </summary>
        public static string StringMaxLengthRule {
            get {
                return ResourceManager.GetString("StringMaxLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a date.
        /// </summary>
        public static string StringToDateException {
            get {
                return ResourceManager.GetString("StringToDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} upper case required.
        /// </summary>
        public static string UCaseStringRequiredRule {
            get {
                return ResourceManager.GetString("UCaseStringRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation - update not allowed.
        /// </summary>
        public static string UpdateNotSupportedException {
            get {
                return ResourceManager.GetString("UpdateNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartDate.
        /// </summary>
        public static string ValueNotSmartDateException {
            get {
                return ResourceManager.GetString("ValueNotSmartDateException", resourceCulture);
            }
        }
    }
}
