//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CULTURE")]
        public string SETTING_NAME_USER_CULTURE {
            get {
                return ((string)(this["SETTING_NAME_USER_CULTURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEFAULT_SCHEMA")]
        public string SETTING_NAME_DEFAULT_SCHEMA {
            get {
                return ((string)(this["SETTING_NAME_DEFAULT_SCHEMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BACKUPS_DAYS")]
        public string SETTING_NAME_BACKUPS_DAYS {
            get {
                return ((string)(this["SETTING_NAME_BACKUPS_DAYS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("moladmin")]
        public string DB_USER {
            get {
                return ((string)(this["DB_USER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iQi_1998")]
        public string DB_PWD {
            get {
                return ((string)(this["DB_PWD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHOW_AUTOPILOT")]
        public string SETTING_NAME_SHOW_AUTOPILOT {
            get {
                return ((string)(this["SETTING_NAME_SHOW_AUTOPILOT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB_VERSION")]
        public string DB_VERSION_VARIABLE {
            get {
                return ((string)(this["DB_VERSION_VARIABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LINK_SEED")]
        public string SETTING_NAME_LINK_SEED {
            get {
                return ((string)(this["SETTING_NAME_LINK_SEED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Backup (*.backup)|*.backup")]
        public string BACKUP_EXTENSION_FILTER {
            get {
                return ((string)(this["BACKUP_EXTENSION_FILTER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("moladmin")]
        public string ADMIN_USER {
            get {
                return ((string)(this["ADMIN_USER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FILES_HOST")]
        public string SETTING_NAME_FILES_HOST {
            get {
                return ((string)(this["SETTING_NAME_FILES_HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FORMAT_GRIDS")]
        public string SETTING_NAME_FORMAT_GRIDS {
            get {
                return ((string)(this["SETTING_NAME_FORMAT_GRIDS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF_PRINTS_FOLDER")]
        public string SETTING_NAME_PDF_PRINTS_FOLDER {
            get {
                return ((string)(this["SETTING_NAME_PDF_PRINTS_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOLEQULE_DB_VERSION")]
        public string SETTING_NAME_MOLEQULE_DB_VERSION {
            get {
                return ((string)(this["SETTING_NAME_MOLEQULE_DB_VERSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_HOST")]
        public string SETTING_NAME_SMTP_HOST {
            get {
                return ((string)(this["SETTING_NAME_SMTP_HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_PORT")]
        public string SETTING_NAME_SMTP_PORT {
            get {
                return ((string)(this["SETTING_NAME_SMTP_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_USER")]
        public string SETTING_NAME_SMTP_USER {
            get {
                return ((string)(this["SETTING_NAME_SMTP_USER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_PWD")]
        public string SETTING_NAME_SMTP_PWD {
            get {
                return ((string)(this["SETTING_NAME_SMTP_PWD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_EMAIL")]
        public string SETTING_NAME_SMTP_EMAIL {
            get {
                return ((string)(this["SETTING_NAME_SMTP_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOLEQULE")]
        public string NAME {
            get {
                return ((string)(this["NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMTP_ENABLE_SSL")]
        public string SETTING_NAME_SMTP_ENABLE_SSL {
            get {
                return ((string)(this["SETTING_NAME_SMTP_ENABLE_SSL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APPLICATION_VERSION")]
        public string SETTING_NAME_APPLICATION_VERSION {
            get {
                return ((string)(this["SETTING_NAME_APPLICATION_VERSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHOW_NULL_RECORDS")]
        public string SETTING_NAME_SHOW_NULL_RECORDS {
            get {
                return ((string)(this["SETTING_NAME_SHOW_NULL_RECORDS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USE_DEFAULT_PRINTER")]
        public string SETTING_NAME_USE_DEFAULT_PRINTER {
            get {
                return ((string)(this["SETTING_NAME_USE_DEFAULT_PRINTER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEFAULT_PRINTER")]
        public string SETTING_NAME_DEFAULT_PRINTER {
            get {
                return ((string)(this["SETTING_NAME_DEFAULT_PRINTER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEFAULT_N_COPIES")]
        public string SETTING_NAME_DEFAULT_N_COPIES {
            get {
                return ((string)(this["SETTING_NAME_DEFAULT_N_COPIES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POSTGRESQL_VERSION")]
        public string SETTING_NAME_POSTGRESQL_VERSION {
            get {
                return ((string)(this["SETTING_NAME_POSTGRESQL_VERSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BACKUPS_HOUR")]
        public string SETTING_NAME_BACKUPS_HOUR {
            get {
                return ((string)(this["SETTING_NAME_BACKUPS_HOUR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BACKUPS_LAST_DATE")]
        public string SETTING_NAME_BACKUPS_LAST_DATE {
            get {
                return ((string)(this["SETTING_NAME_BACKUPS_LAST_DATE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CULTURE")]
        public string SETTING_NAME_APP_CULTURE {
            get {
                return ((string)(this["SETTING_NAME_APP_CULTURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Countries.xml")]
        public string COUNTIES_XML_FILE {
            get {
                return ((string)(this["COUNTIES_XML_FILE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOLEQULE")]
        public string DB_NAME {
            get {
                return ((string)(this["DB_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN_EMAIL")]
        public string SETTING_NAME_ADMIN_EMAIL {
            get {
                return ((string)(this["SETTING_NAME_ADMIN_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN_CONTACT")]
        public string SETTING_NAME_ADMIN_CONTACT {
            get {
                return ((string)(this["SETTING_NAME_ADMIN_CONTACT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLIENTS_CONTACT")]
        public string SETTING_NAME_CLIENTS_CONTACT {
            get {
                return ((string)(this["SETTING_NAME_CLIENTS_CONTACT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUPPORT_CONTACT")]
        public string SETTING_NAME_SUPPORT_CONTACT {
            get {
                return ((string)(this["SETTING_NAME_SUPPORT_CONTACT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLIENTS_EMAIL")]
        public string SETTING_NAME_CLIENTS_EMAIL {
            get {
                return ((string)(this["SETTING_NAME_CLIENTS_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUPPORT_EMAIL")]
        public string SETTING_NAME_SUPPORT_EMAIL {
            get {
                return ((string)(this["SETTING_NAME_SUPPORT_EMAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUPPORT_MOBILE_PHONE")]
        public string SETTING_NAME_SUPPORT_MOBILE_PHONE {
            get {
                return ((string)(this["SETTING_NAME_SUPPORT_MOBILE_PHONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLIENTS_MOBILE_PHONE")]
        public string SETTING_NAME_CLIENTS_MOBILE_PHONE {
            get {
                return ((string)(this["SETTING_NAME_CLIENTS_MOBILE_PHONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN_MOBILE_PHONE")]
        public string SETTING_NAME_ADMIN_MOBILE_PHONE {
            get {
                return ((string)(this["SETTING_NAME_ADMIN_MOBILE_PHONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/gwaihir/monitor/")]
        public string API_URL_MONITOR {
            get {
                return ((string)(this["API_URL_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("monitor.html")]
        public string API_SERVICE_MONITOR {
            get {
                return ((string)(this["API_SERVICE_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("update")]
        public string API_ACTION_MONITOR {
            get {
                return ((string)(this["API_ACTION_MONITOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("moladmin")]
        public string SUPERUSER {
            get {
                return ((string)(this["SUPERUSER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("molservice")]
        public string SERVICES_USER {
            get {
                return ((string)(this["SERVICES_USER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMS_GATEWAY_NAME")]
        public string SETTING_NAME_SMS_GATEWAY_NAME {
            get {
                return ((string)(this["SETTING_NAME_SMS_GATEWAY_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMS_GATEWAY_CODE")]
        public string SETTING_NAME_SMS_GATEWAY_CODE {
            get {
                return ((string)(this["SETTING_NAME_SMS_GATEWAY_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMS_GATEWAY_USER")]
        public string SETTING_NAME_SMS_GATEWAY_USER {
            get {
                return ((string)(this["SETTING_NAME_SMS_GATEWAY_USER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMS_GATEWAY_PWD")]
        public string SETTING_NAME_SMS_GATEWAY_PWD {
            get {
                return ((string)(this["SETTING_NAME_SMS_GATEWAY_PWD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SMS_GATEWAY_ACCOUNT")]
        public string SETTING_NAME_SMS_GATEWAY_ACCOUNT {
            get {
                return ((string)(this["SETTING_NAME_SMS_GATEWAY_ACCOUNT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iQi_1998")]
        public string SERVICES_PASSWORD {
            get {
                return ((string)(this["SERVICES_PASSWORD"]));
            }
        }
    }
}
