//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string ADVISE_TITLE {
            get {
                return ResourceManager.GetString("ADVISE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUALQUIER CAMPO.
        /// </summary>
        public static string ANY_FIELD {
            get {
                return ResourceManager.GetString("ANY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQ moleQule 1.0.
        /// </summary>
        public static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar acción.
        /// </summary>
        public static string CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje de Depuración.
        /// </summary>
        public static string DEBUG_TITLE {
            get {
                return ResourceManager.GetString("DEBUG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos específicos vacíos.
        /// </summary>
        public static string EMPTY_ENTITY_TITLE {
            get {
                return ResourceManager.GetString("EMPTY_ENTITY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        public static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Ayuda        .
        /// </summary>
        public static string LEYENDA {
            get {
                return ResourceManager.GetString("LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string NEWS_TITLE {
            get {
                return ResourceManager.GetString("NEWS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene.
        /// </summary>
        public static string OP_CONTAINS {
            get {
                return ResourceManager.GetString("OP_CONTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string OP_EQUAL {
            get {
                return ResourceManager.GetString("OP_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string OP_GREATER {
            get {
                return ResourceManager.GetString("OP_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string OP_GREATER_OR_EQUAL {
            get {
                return ResourceManager.GetString("OP_GREATER_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string OP_LESS {
            get {
                return ResourceManager.GetString("OP_LESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string OP_LESS_OR_EQUAL {
            get {
                return ResourceManager.GetString("OP_LESS_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empieza por.
        /// </summary>
        public static string OP_STARTS_BY {
            get {
                return ResourceManager.GetString("OP_STARTS_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Esquema:.
        /// </summary>
        public static string SCHEMA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("SCHEMA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Esquema:.
        /// </summary>
        public static string SCHEMA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SCHEMA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Esquema:.
        /// </summary>
        public static string SCHEMA_LOCALIZE_TITLE {
            get {
                return ResourceManager.GetString("SCHEMA_LOCALIZE_TITLE", resourceCulture);
            }
        }
    }
}
