//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQual Ingenieros S.L.
        ///
        ///Emilio Medina Arribas
        ///José Celano Martín
        ///José Gutiérrez Benítez.
        /// </summary>
        public static string ACERCA_DE {
            get {
                return ResourceManager.GetString("ACERCA_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando informe....
        /// </summary>
        public static string BUILDING_REPORT {
            get {
                return ResourceManager.GetString("BUILDING_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si cancela se perderán los últimos cambios realizados.
        ///                               ¿Cancelar?.
        /// </summary>
        public static string CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar acción.
        /// </summary>
        public static string CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nueva configuración de idioma se hará efectiva en la próxima ejecución de la aplicación..
        /// </summary>
        public static string CULTURE_CHANGE_INFO {
            get {
                return ResourceManager.GetString("CULTURE_CHANGE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un elemento de esta entidad que está siendo editado. Para editar otro, por favor, cierre el anterior..
        /// </summary>
        public static string CURRENT_EDITION {
            get {
                return ResourceManager.GetString("CURRENT_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay elementos en edición ¿Está seguro de que desea cerrar?.
        /// </summary>
        public static string CURRENT_EDITION_CLOSE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el elemento. Está siendo editado.
        /// </summary>
        public static string CURRENT_EDITION_DELETE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la eliminación del elemento seleccionado?.
        /// </summary>
        public static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El borrado total de una Schema puede tardar algunos minutos.
        ///      ¿Confirmar la eliminación de la Schema seleccionada?.
        /// </summary>
        public static string DELETE_CONFIRM_SCHEMA {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrando el elemento seleccionado....
        /// </summary>
        public static string DELETING {
            get {
                return ResourceManager.GetString("DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro elemento con ese códígo..
        /// </summary>
        public static string DUPLICATED_CODE {
            get {
                return ResourceManager.GetString("DUPLICATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        public static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando fichero {0}....
        /// </summary>
        public static string EXPORTING_PDF {
            get {
                return ResourceManager.GetString("EXPORTING_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha definido el tipo {0} en el manejador de formularios..
        /// </summary>
        public static string FORM_NOT_FOUND {
            get {
                return ResourceManager.GetString("FORM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible borrar la Schema activa..
        /// </summary>
        public static string INDISPENSABLE_SCHEMA {
            get {
                return ResourceManager.GetString("INDISPENSABLE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;{0}&quot; contiene datos no válidos..
        /// </summary>
        public static string INVALID_FIELD_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FIELD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo modificado contiene datos no válidos..
        /// </summary>
        public static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible borrar un elemento Anulado.
        /// </summary>
        public static string ITEM_ANULADO_NO_DELETE {
            get {
                return ResourceManager.GetString("ITEM_ANULADO_NO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible editar un elemento Anulado.
        /// </summary>
        public static string ITEM_ANULADO_NO_EDIT {
            get {
                return ResourceManager.GetString("ITEM_ANULADO_NO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos....
        /// </summary>
        public static string LOADING_DATA {
            get {
                return ResourceManager.GetString("LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incializando y cargando datos de la empresa.
        /// </summary>
        public static string LOADING_SCHEMA {
            get {
                return ResourceManager.GetString("LOADING_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible editar el elemento seleccionado.
        ///Otro usuario está modificándolo en este momento. .
        /// </summary>
        public static string LOCK_ERROR {
            get {
                return ResourceManager.GetString("LOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error autentificando al usuario por defecto..
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha inicializado el formulario principal en el manejador de formularios.
        /// </summary>
        public static string MAINFORM_NOT_DEFINED {
            get {
                return ResourceManager.GetString("MAINFORM_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos disponibles para realizar una selección específica para este tipo de informe..
        /// </summary>
        public static string NO_DATA_ENTITY {
            get {
                return ResourceManager.GetString("NO_DATA_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para imprimir..
        /// </summary>
        public static string NO_DATA_REPORTS {
            get {
                return ResourceManager.GetString("NO_DATA_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no puede ser eliminado.
        /// </summary>
        public static string NO_DELETE_USER {
            get {
                return ResourceManager.GetString("NO_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe aplicación predeterminada para envío de correos electrónicos.
        /// </summary>
        public static string NO_EMAIL_CLIENT {
            get {
                return ResourceManager.GetString("NO_EMAIL_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dispone de permisos y no se podrá abrir el formulario..
        /// </summary>
        public static string NO_GET_PERMISSION {
            get {
                return ResourceManager.GetString("NO_GET_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado elementos coincidentes.
        /// </summary>
        public static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento de la lista.
        /// </summary>
        public static string NO_SELECTED {
            get {
                return ResourceManager.GetString("NO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas introducidas no son iguales.
        /// </summary>
        public static string NOT_EQUAL_PASS {
            get {
                return ResourceManager.GetString("NOT_EQUAL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos una letra minúscula..
        /// </summary>
        public static string NOT_LCASE_PASS {
            get {
                return ResourceManager.GetString("NOT_LCASE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos un número..
        /// </summary>
        public static string NOT_NUMBER_PASS {
            get {
                return ResourceManager.GetString("NOT_NUMBER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos una letra mayúscula..
        /// </summary>
        public static string NOT_UCASE_PASS {
            get {
                return ResourceManager.GetString("NOT_UCASE_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la anulación del elemento seleccionado?.
        /// </summary>
        public static string NULL_CONFIRM {
            get {
                return ResourceManager.GetString("NULL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abriendo el cliente de correo predeterminado....
        /// </summary>
        public static string OPENING_EMAIL_CLIENT {
            get {
                return ResourceManager.GetString("OPENING_EMAIL_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible realizar la operación.
        ///.
        /// </summary>
        public static string OPERATION_ERROR {
            get {
                return ResourceManager.GetString("OPERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación finalizada con éxito.
        /// </summary>
        public static string OPERATION_OK {
            get {
                return ResourceManager.GetString("OPERATION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha escrito una contraseña. ¿Está seguro de que desea que el usuario no posea contraseña?.
        /// </summary>
        public static string PASSWORD_NULL {
            get {
                return ResourceManager.GetString("PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescando datos....
        /// </summary>
        public static string REFRESHING_DATA {
            get {
                return ResourceManager.GetString("REFRESHING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando lista....
        /// </summary>
        public static string REFRESHING_LIST {
            get {
                return ResourceManager.GetString("REFRESHING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo datos seleccionados....
        /// </summary>
        public static string RETRIEVING_DATA {
            get {
                return ResourceManager.GetString("RETRIEVING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando....
        /// </summary>
        public static string SAVING {
            get {
                return ResourceManager.GetString("SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible borrar el esquema activo..
        /// </summary>
        public static string SCHEMA_ACTIVE {
            get {
                return ResourceManager.GetString("SCHEMA_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de esquemas de la aplicación ha alcanzado el límite permitido..
        /// </summary>
        public static string SCHEMA_MAX {
            get {
                return ResourceManager.GetString("SCHEMA_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para acceder a esta esquema.
        /// </summary>
        public static string SCHEMA_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SCHEMA_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando mensaje....
        /// </summary>
        public static string SENDING_EMAIL {
            get {
                return ResourceManager.GetString("SENDING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + = Agregar.
        /// </summary>
        public static string STATUS_GENERICO {
            get {
                return ResourceManager.GetString("STATUS_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la contraseña son incorrectos..
        /// </summary>
        public static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando permisos....
        /// </summary>
        public static string VALIDATION_MSG {
            get {
                return ResourceManager.GetString("VALIDATION_MSG", resourceCulture);
            }
        }
    }
}
